using System.Collections.Generic;
using System.Text;

namespace AirGestureAI.ApiDocs
{
    /// <summary>
    /// Exports an API documentation tree to a self-contained HTML document.
    /// </summary>
    public sealed class HtmlDocumentationExporter
    {
        /// <summary>
        /// Converts a list of <see cref="ApiTypeDoc"/> entries into an HTML string.
        /// </summary>
        public string Export(IReadOnlyList<ApiTypeDoc> docs, string assemblyName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\">");
            sb.AppendLine("<head>");
            sb.AppendLine($"  <title>{assemblyName} – API Reference</title>");
            sb.AppendLine("  <meta charset=\"UTF-8\">");
            sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
            sb.AppendLine("  <style>");
            sb.AppendLine("    body { font-family: Segoe UI, sans-serif; background:#121212; color:#e0e0e0; margin:0; padding:20px; }");
            sb.AppendLine("    h1 { color:#0D6EFD; } h2 { color:#4FC3F7; border-bottom:1px solid #333; padding-bottom:4px; }");
            sb.AppendLine("    table { border-collapse:collapse; width:100%; margin-bottom:24px; }");
            sb.AppendLine("    th,td { border:1px solid #333; padding:8px 12px; text-align:left; font-size:13px; }");
            sb.AppendLine("    th { background:#1E1E1E; color:#0D6EFD; }");
            sb.AppendLine("    code { background:#1E1E1E; padding:2px 6px; border-radius:4px; }");
            sb.AppendLine("    .deprecated { color:#FF7043; }");
            sb.AppendLine("    .ns { color:#888; font-size:13px; }");
            sb.AppendLine("  </style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine($"  <h1>{assemblyName} API Reference</h1>");
            sb.AppendLine("  <p><em>Generated by AirGesture AI Developer Center</em></p>");

            foreach (var type in docs)
            {
                sb.AppendLine($"  <h2><code>{type.Name}</code></h2>");
                sb.AppendLine($"  <p class=\"ns\">Namespace: <code>{type.Namespace}</code></p>");
                if (!string.IsNullOrEmpty(type.Summary))
                    sb.AppendLine($"  <p>{type.Summary}</p>");

                if (type.Members.Count > 0)
                {
                    sb.AppendLine("  <table>");
                    sb.AppendLine("    <thead><tr><th>Member</th><th>Kind</th><th>Return Type</th><th>Deprecated</th></tr></thead>");
                    sb.AppendLine("    <tbody>");
                    foreach (var m in type.Members)
                    {
                        var depCell = m.IsDeprecated
                            ? "<td class=\"deprecated\">⚠️ Yes</td>"
                            : "<td>No</td>";
                        sb.AppendLine($"      <tr><td><code>{m.Name}</code></td><td>{m.MemberType}</td><td><code>{m.ReturnType}</code></td>{depCell}</tr>");
                    }
                    sb.AppendLine("    </tbody>");
                    sb.AppendLine("  </table>");
                }
            }

            sb.AppendLine("</body></html>");
            return sb.ToString();
        }
    }
}
