using System.Collections.Generic;
using System.Text;

namespace AirGestureAI.ApiDocs
{
    /// <summary>
    /// Exports an API documentation tree to GitHub-flavored Markdown.
    /// </summary>
    public sealed class MarkdownExporter
    {
        /// <summary>
        /// Converts a list of <see cref="ApiTypeDoc"/> entries into a Markdown string.
        /// </summary>
        public string Export(IReadOnlyList<ApiTypeDoc> docs, string assemblyName)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# {assemblyName} API Reference");
            sb.AppendLine();
            sb.AppendLine($"> Generated by AirGesture AI Developer Center");
            sb.AppendLine();

            foreach (var type in docs)
            {
                sb.AppendLine($"## `{type.Name}`");
                sb.AppendLine();
                sb.AppendLine($"**Namespace**: `{type.Namespace}`");
                sb.AppendLine();
                if (!string.IsNullOrEmpty(type.Summary))
                {
                    sb.AppendLine(type.Summary);
                    sb.AppendLine();
                }

                if (type.Members.Count > 0)
                {
                    sb.AppendLine("| Member | Kind | Return Type | Deprecated |");
                    sb.AppendLine("|--------|------|-------------|------------|");
                    foreach (var m in type.Members)
                    {
                        var deprecated = m.IsDeprecated ? "⚠️ Yes" : "No";
                        sb.AppendLine($"| `{m.Name}` | {m.MemberType} | `{m.ReturnType}` | {deprecated} |");
                    }
                    sb.AppendLine();
                }
            }

            return sb.ToString();
        }
    }
}
